### PR TITLE
Disable background throttling

### LINKED ISSUE #154: MPRIS player sometimes does not update when changing track
If I listen to some album, the title of a track sometime remains after it ends. The pause/play icon is also wrong at certain moments (showing play when the song is playing and pause when it is paused).

The MPRIS player only updates every 2 or 3 tracks, instead of always displaying the correct information about the current song.

tidal
In this example, the notification controls still display the first track, "Needle in the Hay", when Tidal is actually playing "Clementine", the third song.

### PR DESCRIPTION
**Pull request by vincens2005**
Background throttling slows down setInterval when the window isn't focused, causing issues with muting and player updating.

Probably fixes #154

### CODE REVIEW

**Comment by Mar0xy** [comment]
How does resource consumption compare between it being off and on.

**Comment by Mastermindzh** [comment]
I haven't encountered this issue either, but I use i3wm so I don't know whether it actually is considered "background" or not.
The option certainly can't hurt though I'd make it a toggle in the settings (with the default being true (e.g disabled).

@vincens2005 , would you be willing to make that change?
I can do it as well, but only in the weekend :)

**Comment by vincens2005** [comment]
Sure I can do that sometime in the next few days 👍

**Comment by vincens2005** [comment]
okay I did it

**Comment by vincens2005** [comment]
@Mastermindzh ?

**Comment by Mastermindzh** [comment]
@vincens2005 , sorry! I will have a look soon!

**Review by Mastermindzh — APPROVED** [review]
Changes look great, I will (hopefully) merge this evening but tomorrow at the latest!

**Pull request merged**
