### PR TITLE
Bump electron version

### LINKED ISSUE #145: failed to install widevine components
Screenshot from 2022-06-10 23-12-55

### PR DESCRIPTION
**Pull request by alternateved**
Hello,

I believe that simple update of electron version is enough to fix #145. 

Currently I am trying to package tidal-hifi with Nix and I am using [tidal-hifi_3.1.1_amd64.deb](https://github.com/Mastermindzh/tidal-hifi/releases/download/3.1.1/tidal-hifi_3.1.1_amd64.deb) binary. With never version of electron this error does not happen. Are there any objections to using the latest version?

Best wishes,
alternateved

### CODE REVIEW

**Comment by Mastermindzh** [comment]
In earlier attempts Tidal completely stopped working when updating to anything newer.

Since Tidal has done a few updates we might be able to bump it now. I'll test it tomorrow.

@Mar0xy, care to run a test in your system as well? Would be appreciated!

**Comment by alternateved** [comment]
I also had to update main code a little, as advised here: https://github.com/castlabs/electron-releases#using

Otherwise, the DRM would be disabled.

**Comment by Mar0xy** [comment]
This does indeed work for me I also got curious and tried to see if the newer version fixes the weird glitch that the SetInterval got with the new tidal update but it didn't.

**Comment by Mastermindzh** [comment]
@alternateved,

Sure, feel free to update the readme for Nix 😄

**Pull request merged**
