### PR TITLE
[BUG] Update electron to 24.1.2 for fixing tray single click bug

### PR DESCRIPTION
**Pull request by thanasistrisp**
By updating electron and making some small fixes, single tray icon click is finally working. It was an upstream bug that fixed only in versions 22.x (see [here](https://github.com/electron/electron/issues/36283)). It should now be fixed for most desktop environments.
Now, when pressing tray icon, the window shows or hides appropriately. Previously, I could not have single left click, as it showed the menu (like pressing right click). I use arch Linux with KDE.
~~Also, I updated some dependencies without breaking changes.~~ Resolved merge conflict by reverting to main dependencies except of electron version only.

### CODE REVIEW

**Comment by Mastermindzh** [comment]
Hey @thanasistrisp,

Versions that are **built** using v20+ electron versions only display a white screen after launch.
You can try it out using `npm run build-base` and then running `./dist/tidal-hifi`

That is the exact same reason why the original code (that you restore) had been removed.

If you can get it working without a white screen **after** building then please let me know 😄

**Comment by thanasistrisp** [comment]
> Hey @thanasistrisp,
> 
> Versions that are **built** using v20+ electron versions only display a white screen after launch. You can try it out using `npm run build-base` and then running `./dist/tidal-hifi`
> 
> That is the exact same reason why the original code (that you restore) had been removed.
> 
> If you can get it working without a white screen **after** building then please let me know smile

I did not notice any problem with white screen else if I had the problem I would not open pull request. It just needs to explicitly say `sanbox:false` as in newer version of electrons the default is true.

**Comment by Mastermindzh** [comment]
I'll try again.

I take it the change to the adblock URL is absolutely needed before a new release since it's blocking the settings?

(I don't have a tidal account with ads)

**Comment by thanasistrisp** [comment]
> I'll try again.
> 
> I take it the change to the adblock URL is absolutely needed before a new release since it's blocking the settings?
> 
> (I don't have a tidal account with ads)
Just try npm install before run. And clone my repository exactly as I have it. Latest commit is not so urgent, but is shows some more account settings that the previous filter blocked.

**Comment by Mastermindzh** [comment]
Alright, that seems to have done the trick. Didn't know the default changed.
Could you remove the unnecessary package-lock changes please 😄 ?

You just need the following changes to make it all work: 
image

Other than that we can merge these changes too and release a version 5 this weekend 😄

**Comment by Mastermindzh** [comment]
@thanasistrisp , I can do it myself as well if you want, I don't mind 😄

**Comment by thanasistrisp** [comment]
> @thanasistrisp , I can do it myself as well if you want, I don't mind 😄  (you gave me contributor on the fork anyway)

Do it yes.

**Pull request closed without merging**
