### PR TITLE
Update to Electron 15 and add Flatpak to README

### LINKED ISSUE #55: Release on flatpak
This would be great, I prefer it over snap/installing from source. It will enable updates to automatically be installed.

### LINKED ISSUE #130: Update to Electron 9+
Issues arrive when we build the app with electron-builder and Electron 9+.

Issue #129, is the first issue but from that I got the following:

- Audio doesn't reliably play (it does ... sometimes... but restarting the app over and over breaks it eventually)
- Hotkeys don't work anymore either
- The API doesn't seem to start
- If you open the settings window you can't close it

The weird thing is that when we use electron in dev mode, all the stuff works.
I will have to debug it later, but 2.8.2 fixes the issue by reverting to electron 8.5.2

@Mar0xy , I reverted the electron version because of this. I will look into updating it again later.

### PR DESCRIPTION
**Pull request by Mar0xy**
I have now checked all API changes and can say that it works fine for me now besides the settings window.hide and window.restart not working This is only updating to 15 cause wvcus is broken for tidal for some reason.

also due to security increases window.(function) no longer works

(Needs Node 14 or higher to work properly during dev)

Closes #130 and Closes #55 due to the addition of flatpak to readme

### CODE REVIEW

**Comment by Mar0xy** [comment]
https://user-images.githubusercontent.com/8841466/164584516-d32f8973-208f-4ce8-8e50-9b18405e9323.mp4

**Comment by Mastermindzh** [comment]
Great to see so much work from you @Mar0xy,

Can you sum up the things that do not work yet?
I will have some spare time tonight (after 9-ish) and tomorrow.

**Comment by Mar0xy** [comment]
I didn't check API and Hotkeys but everything else should work.

**Comment by Mastermindzh** [comment]
Tested and approved. Will merge!

**Pull request merged**
