### PR TITLE
Add cors to the express api

### PR DESCRIPTION
**Pull request by Mjokfox**
Ive been trying to use the api, but couldnt get it working except in the browser for some reason. Adding cors to the api made it work on my end.

- added cors module
- made the expressApp use cors

### CODE REVIEW

**Comment by Mastermindzh** [comment]
Whilst CORS in and of itself isn't a bad feature it probably shouldn't be added because something didn't work for you 😄.
Can you explain what didn't work? Maybe I can help a bit.

Other than that, adding CORS is a good idea, I'll look into it.
I would want it behind settings so that people can actually change the origins.

**Comment by Mjokfox** [comment]
So I've made a plugin for Vencord that shows what I'm current listening as my discord status. And i am using this api to get that. So i do a basic get request to http://localhost:47836/current. This works just fine when i do it in a basic nodejs environment. But with the exact same code in the plugin, it returns 'TypeError: Failed to fetch', apparently this is a CORS problem. I've tried plenty of headers with no avail. 
I thought since i had issues with it, others may too.

**Comment by Mastermindzh** [comment]
Alright, don't know Vencord but it makes sense if you're doing it from another app that CORS might be implemented there.

I probably have time in the weekend to add the settings and release a new version 😄

**Comment by Mastermindzh** [comment]
It was my bad mate... the API is already restricted to localhost so no need for settings.
I will merge your PR. 

PS: I did remove package-lock from your PR 😄

**Pull request merged**
