### PR TITLE
Fix album not updating on playlists

### PR DESCRIPTION
**Pull request by drom98**
After reading [this](https://github.com/Mastermindzh/tidal-hifi/issues/194) issue, I've take a look at the code and noticed that the current playing title was not being properly fetched anymore since Tidal changed the css class that we use to grab the correct element. 
Only mixes and playlists would be affected because when listening to an album we get the name from the header instead of the list of musics.

### CODE REVIEW

**Comment by Mastermindzh** [comment]
image

We might want to try and find a more stable tag again (if provided, which is not always the case) as both of these now return null for me when playing items from a playlist :/

**Comment by Mar0xy** [comment]
>  (if provided, which is not always the case)

It indeed doesn't have a tag that never changes. though one thing I noticed is that there are api calls tidal does which gets track information, artist info, lyrics and etc though they require the authorization header which I don't know if you can send requests with those cookies included just from the browser itself.

but here are the URLs:
`https://listen.tidal.com/v1/albums/(albumid)?countryCode=US`
`https://listen.tidal.com/v1/tracks/(trackid)?countryCode=US`

We already grab the track id so we don't need to add some fancy things for grabbing it and when it comes to the album you can also just directly get the album info from the track as this is how the json is constructed

```json
{
    "id": 91887980,
    "title": "Running up That Hill",
    "duration": 294,
    "replayGain": -8.29,
    "peak": 0.861143,
    "allowStreaming": true,
    "streamReady": true,
    "streamStartDate": "2010-01-05T00:00:00.000+0000",
    "premiumStreamingOnly": false,
    "trackNumber": 16,
    "volumeNumber": 1,
    "version": null,
    "popularity": 0,
    "copyright": "℗ 2010 Lionsgate",
    "url": "http://www.tidal.com/track/91887980",
    "isrc": "USCK30904716",
    "editable": false,
    "explicit": false,
    "audioQuality": "LOSSLESS",
    "audioModes": ["STEREO"],
    "artist": {
        "id": 9022,
        "name": "Placebo",
        "type": "MAIN",
        "picture": "e03ec93d-645a-4bf6-b666-5ab17fd5a98e"
    },
    "artists": [{
        "id": 9022,
        "name": "Placebo",
        "type": "MAIN",
        "picture": "e03ec93d-645a-4bf6-b666-5ab17fd5a98e"
    }],
    "album": {
        "id": 91887964,
        "title": "Daybreakers (Original Motion Picture Soundtrack)",
        "cover": "48f4de0e-45c2-4e46-be80-fad72ffd1daa",
        "vibrantColor": "#b6322f",
        "videoCover": null
    },
    "mixes": {
        "TRACK_MIX": "001270eadfa689e873cc406755a4b4"
    }
}
```

**Comment by Mar0xy** [comment]
The auth header also doesn't change and stays the same until you obviously log out and back in.

**Comment by Mastermindzh** [comment]
Hey @Mar0xy,

Might be an interesting way to go, I'll have to have a look later!
I'm not against using the API if we can piggyback ;)

**Comment by Mar0xy** [comment]
Yea, as this would be the easiest and most stable solution out of everything

**Comment by Mar0xy** [comment]
@Mastermindzh Any progress/updates on this as it's been 4-5 months already.

**Comment by Mastermindzh** [comment]
I haven't had a look yet, sorry.
I can merge this temporary fix for now (on saturday) and pick this up later.

**Pull request merged**
