### PR TITLE
Add instruction for installation via Nix

### PR DESCRIPTION
**Pull request by alternateved**
Hello,

I have updated README with instructions for installation via Nix. 
If you don't mind I've also changed a few small things to make it look more consistent.  

Kind wishes,
alternateved

### CODE REVIEW

**Comment by Mastermindzh** [comment]
I don't mind, thanks for adding the instructions.

Can you do a quick:
`npx markdown-toc README.md` please 😄 ?

It will add/change the heading corrections you made in the table of contents.

**Comment by alternateved** [comment]
Ah, right! I forgot about the table of contents. Should be fixed now. Thanks for noting that.

**Comment by alternateved** [comment]
Ah, wait, one last thing.

**Comment by Mastermindzh** [comment]
Thanks for the contribution!

**Pull request merged**
