### PR TITLE
Discord RPC Replace Ratelimiter

### PR DESCRIPTION
**Pull request by Mar0xy**
As suggested I replaced the ratelimiter with an system which only updates if the song gets paused, started or switched

### CODE REVIEW

**Comment by Mastermindzh** [comment]
You absolute madman! I just finished publishing 2.1.0!

**Comment by Mar0xy** [comment]
That was timing :laughing:
Check it out and give feedback on it.

**Comment by Mar0xy** [comment]
I have also taken another look into the artist name and noticed that when the Explicit icon used to come up it would be picked up aswell after snooping around a bit more I found the correct class and after using it for a while I haven't run into any issue.

**Comment by Mastermindzh** [comment]
Closed because of https://github.com/Mastermindzh/tidal-hifi/pull/42

**Pull request closed without merging**
