### PR TITLE
Muting artists automatically

### PR DESCRIPTION
**Pull request by Mastermindzh**
- Added the ability to mute artists automatically
- Added better error handling for discord rpc

### CODE REVIEW

**Comment by vincens2005** [comment]
It works. The only thing is that the artist name for ads is TIDAL, not Tidal, so you need to change it for ads to be muted. Other than that, it's great.

**Comment by Mastermindzh** [comment]
I will change and release it today then. Thanks for the double-check! Glad we got that sorted.

**Comment by vincens2005** [comment]
Cool!

**Comment by Mastermindzh** [comment]
Make that tomorrow. Life happens 😄

**Comment by Mastermindzh** [comment]
Here we go boys! 

Production build has started.

**Pull request merged**
