### PR TITLE
Adding enable-gpu-rasterization to main.js 

### PR DESCRIPTION
**Pull request by licentiapoetica**
Adding enable-gpu-rasterization

### CODE REVIEW

**Comment by Mar0xy** [comment]
I think this should be optional as not everyone needs this and as it would end up taking GPU resources for people who might need them.

**Comment by licentiapoetica** [comment]
> I think this should be optional as not everyone needs this and as it would end up taking GPU resources for people who might need them.

I actually only wanted to add it as a new branch, not in the master branch, so if someone has this problem they can easily check it out

**Comment by licentiapoetica** [comment]
But is there a significant downside in just having this enabled by default? I guess if some people install this app they want it to perform at it's best and not have to tinker, it would be good to check if this being enabled by default has downsides to it, or is this maybe going to cause issues for people not having a dedicated gpu?

**Comment by Mar0xy** [comment]
> cause issues for people not having a dedicated gpu?
This exactly people with non-dedicated gpu will lose performance in other apps if this gets enabled by default

**Comment by Mastermindzh** [comment]
@licentiapoetica, I was going to say the same thing as @Mar0xy, please create a setting 😄 

If you don't do it I will wrap it in a setting with a small revamp on the settings menu later, but you'd have to compile yourself meanwhile.

**Comment by licentiapoetica** [comment]
You are right, a setting would be the best option, I don't know if my knowledge is sufficient though, so I think it is a good idea if you would add it, but I will try it aswell and see where it goes.

**Comment by licentiapoetica** [comment]
I am reopening the pull request since this is actually needed on all my system to use tidal-hifi the way it's intended to be used, please see the following for further proof and how it affects the performance.

https://github.com/Mastermindzh/tidal-hifi/issues/132#issuecomment-1118283079
https://github.com/Mastermindzh/tidal-hifi/issues/132#issuecomment-1118392391

**Comment by Mastermindzh** [comment]
Included in [3.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/3.1.0) as an optional setting :) 
Thanks again!

**Pull request closed without merging**
